### ISSUE TITLE
Remove special treatment of trait methods in bundling for fstar

### ISSUE THREAD

**Issue by maximebuyse** [hacspec/hax#1078] opened 2024-10-30 16:20 UTC
When possible, the special treatment for the fstar backend implemented in https://github.com/hacspec/hax/pull/1075 (see the discussion in the PR for the reason) should be removed. It is a hack to allow type class methods to be accessible in the original modules and not only in the bundle. But it is specific to the use we have for type classes for the translation of traits.

**Comment by franziskuskiefer** [comment] 2024-11-26 07:54
@W95Psp how is this related to #412 ?

**Comment by W95Psp** [comment] 2024-11-26 08:01
Fixing #412 will indeed fix this issue as well, thanks Franziskus!

The special treatment Maxime talks about is related to the fact F* creates a top level function per type class method in the module the type class is defined in. So this will indeed go away as soon we stop replying on F* typeclasses.

**Comment by franziskuskiefer** [comment] 2024-11-26 08:03
Ok, closing this as duplicate of #412 then. It doesn't sound like we will treat this issue separately.

**Closed by franziskuskiefer** 2024-11-26 08:03 UTC
Labels: engine, f*
