### ISSUE TITLE
Frontend Performance Problem

### ISSUE THREAD

**Issue by paulmure** [hacspec/hax#863] opened 2024-08-29 22:27 UTC
# Issue
We discovered a performance issue in the frontend when using the `tock_registers` crate.
[https://docs.rs/tock-registers/latest/tock_registers/](https://docs.rs/tock-registers/latest/tock_registers/)

# Details
There is a macro called `register_bitfields` which makes it easy to defined type-checked memory mapped registers with bitfields. And it can be used like so:
```rust
tock_registers::register_bitfields![u64,
    REG [
        FIELD1 8,
        FIELD2 8,
        FIELD3 8,
        FIELD4 8,
        FIELD5 8,
        FIELD6 8,
        FIELD7 8,
        FIELD8 8,
    ],
];
```

We observed an exponential blowup in the size of the JSON exported by the frontend w.r.t. to the number of bitfields in a register. The example here generates a JSON that takes 2GB on disk. However, `rustc` has no problem compiling the code above and only takes a fraction of a second. The extracted code from the backend also looks normal as expected, where the final output only grows linearly w.r.t. to the number of bitfields.

In a realistic project that uses this macro, hax simply gets killed by the OS due to OOM after using over 80GB of memory.

# Potential Causes

- Lack of interning: Neither the frontend nor the backend employs any form of interning to curb memory use.
- JSON serialization: JSON is an inherently inefficient serialization format.

There might also be issues with how macros are expanded that I'm not aware of.

# Solution
Unfortunately there doesn't seem to be an easy solution. Solving issues like this and similar scaling problems would likely involve major refactoring across the hax codebase.

**Comment by W95Psp** [comment] 2024-08-30 05:04
Hi, thanks for your report!
Indeed, hax was developed entirely in the mindset of making as many Rust language feature as possible as fast as possible.
So no effort has been put inside optimization.

Guillaume and I have been discussing an approach to do cheap interning, summarized there: https://github.com/hacspec/hax/issues/754.

The frontend actually serializes to a binary serialization format internally. It's only when calling the frontend that we export to JSON.
So I suspect the problem is very high redundancy of something in the extraction.

I see a few ways of finding out what is the problem:
 - `cargo expand` on your code, to see if indeed, this macro deosn't generate tons and tons of code
 - `cargo hax json -o - | jless`, to get a sense of what is being exported so many times

More that the format, I suspect the fact we output things like DefIds and types at every point might be the issue. Sometimes a very nested expression can refer the same complicated and lengthy type over and over. Same thing for trait instantiations.

**Comment by paulmure** [comment] 2024-08-30 23:33
> Hi, thanks for your report! Indeed, hax was developed entirely in the mindset of making as many Rust language feature as possible as fast as possible. So no effort has been put inside optimization.
> 
> Guillaume and I have been discussing an approach to do cheap interning, summarized there: #754.
> 
> The frontend actually serializes to a binary serialization format internally. It's only when calling the frontend that we export to JSON. So I suspect the problem is very high redundancy of something in the extraction.
> 
> I see a few ways of finding out what is the problem:
> 
> * `cargo expand` on your code, to see if indeed, this macro deosn't generate tons and tons of code
> * `cargo hax json -o - | jless`, to get a sense of what is being exported so many times
> 
> More that the format, I suspect the fact we output things like DefIds and types at every point might be the issue. Sometimes a very nested expression can refer the same complicated and lengthy type over and over. Same thing for trait instantiations.

If I run `cargo hax json` on the output obtained from `cargo expand`, the JSON output is only 2MB instead of 2GB. It does seem like there's some issue with how macros are expanded.

**Comment by W95Psp** [comment] 2024-09-02 06:17
Huh, this is surprising! That really sounds like a very weird bug!
Will try to find time to investigate, but I'm soon taking some holidays, so I don't know when :/

**Comment by W95Psp** [comment] 2024-10-23 15:41
Hi, I tried to reproduce with hax PR #1029 (which should be merged in main soon), and I think the problem is completely gone!

**Closed** 2024-10-23 16:08 UTC
Labels: bug, frontend
