### ISSUE TITLE
[Feature request] Loop invariant

### ISSUE THREAD

**Issue by mamonet** [hacspec/hax#774] opened 2024-07-15 15:42 UTC
It would be great if we can define loop invariant to keep track on updated variable inside the loop body for each iteration. Here is a use case for the feature
In the following loop body we need to have invariant for updated variable `zeta_i` to tell the resolver that its value is still inside the boundaries https://github.com/cryspen/libcrux/blob/ml-kem-lax-check/libcrux-ml-kem/src/ntt.rs#L61-L63

The feature can replace the assumptions in this code https://github.com/cryspen/libcrux/blob/ml-kem-panic-free/libcrux-ml-kem/src/ntt.rs#L66-L69 to make it verify.

**Comment by W95Psp** [comment] 2024-07-15 15:45
Hey, thanks for the issue! That's a duplicate of https://github.com/hacspec/hax/issues/605 though. Can you comment in there and close that one?

**Closed** 2024-07-15 15:46 UTC
