### ISSUE TITLE
No renaming of enum variant constructor as closure in cyclic dependencies bundling

### ISSUE THREAD

**Issue by maximebuyse** [hacspec/hax#1021] opened 2024-10-22 09:44 UTC
```rust
pub mod a {
    pub enum Context {
        A(i32),
        B(i32)
    }
    pub fn f () -> Context {super::b::h()}
    impl Context {
        pub fn test (x: Option<i32>) -> Option<Context> {
            x.map(Self::A)
        }
    }
}
pub mod b {
    pub fn h () -> super::a::Context {
        super::a::Context::A(1)
    }
}
```
[Open this code snippet in the playground](https://hax-playground.cryspen.com/#fstar/21672cd0da/gist=02e1f1d6a4c867fd25f808a5c95689e5)

We produce `Playground.A.Context.v_A` for `Self::A` but it should be renamed to belong to the bundle.

**Comment by maximebuyse** [comment] 2024-10-22 09:46
Using the variant constructor as a closure seems to refer to something that doesn't exist even when bundling is not involved:

```rust

pub enum Context {
    A(i32),
    B(i32)
}
impl Context {
    pub fn test (x: Option<i32>) -> Option<Context> {
        x.map(Self::A)
    }
}

```
[Open this code snippet in the playground](https://hax-playground.cryspen.com/#fstar/21672cd0da/gist=23a4a138fa1f6c4fb6919105572f4941)

@W95Psp Is this supposed to function?

**Comment by maximebuyse** [comment] 2024-10-22 12:52
> Using the variant constructor as a closure seems to refer to something that doesn't exist even when bundling is not involved:
> 
> pub enum Context {
>     A(i32),
>     B(i32)
> }
> impl Context {
>     pub fn test (x: Option<i32>) -> Option<Context> {
>         x.map(Self::A)
>     }
> }
> 
> [Open this code snippet in the playground](https://hax-playground.cryspen.com/#fstar/21672cd0da/gist=23a4a138fa1f6c4fb6919105572f4941)
> 
> [@W95Psp](https://github.com/W95Psp) Is this supposed to function?

We produce the following fstar for this:

```
module Playground
#set-options "--fuel 0 --ifuel 1 --z3rlimit 15"
open Core
open FStar.Mul

type t_Context =
  | Context_A : i32 -> t_Context
  | Context_B : i32 -> t_Context

let impl__Context__test
      (x: Core.Option.t_Option i32)
    : Core.Option.t_Option t_Context =
  Core.Option.impl__map #i32
    #t_Context
    x
    Playground.Context.v_A
```

I think just replacing `Playground.Context.v_A` by `Context_A` would work in f*. One way to do that would be to recognize `GlobalName` (if we do it in `import_thir`) or `GlobalVar` (if we add a phase for this, which is probably the best choice) for which the id is `path_to_enum::Variant::Ctor` and replace them with the corresponding `Construct` expression.

**Comment by maximebuyse** [comment] 2024-10-22 12:56
The solution should also work for structs:

```rust
struct Test(i32);
impl Test {
    pub fn test (x: Option<i32>) -> Option<Test> {
        x.map(Self)
    }
}
```
[Open this code snippet in the playground](https://hax-playground.cryspen.com/#fstar/21672cd0da/gist=6e93c68c42baae44f76c9aac2cdeb12b)

**Comment by maximebuyse** [comment] 2024-10-22 13:06
The case of structs is very similar (we get a `GlobalVar` expr with the id of the struct followed by `Ctor`). Maybe the solution would be to add a phase catching this kind of expressions, looking for the corresponding type definition (we need to get some information like `is_struct`) and replace with the right expression. It is probably more complicated than a `Construct` expression as this needs to be applied. so maybe we can do something like `(fun x -> Construct x)`.

**Comment by W95Psp** [comment] 2024-10-23 15:46
This is a duplicate of #914, closing.

**Comment by maximebuyse** [comment] 2024-10-24 15:41
#914 is now fixed but we need to rename even with the `Ctor` at the end of names

**Closed** 2024-10-28 11:39 UTC
Labels: bug, engine
